import {
  CompanyProfile,
  Subscription,
  BillingHistory,
  User,
  SystemSettings,
  NotificationSettings,
  DEFAULT_SYSTEM_SETTINGS,
  DEFAULT_NOTIFICATION_SETTINGS,
} from '@/types/settings';

export const mockCompanyProfile: CompanyProfile = {
  id: 'company-1',
  name: 'TechCorp UAE LLC',
  nameAr: 'تك كورب الإمارات ذ.م.م',
  tradeLicenseNumber: 'TL-2024-123456',
  establishmentCard: 'EC-2024-789012',
  address: 'Office 501, Business Bay Tower',
  city: 'Dubai',
  emirate: 'Dubai',
  poBox: '12345',
  phone: '+971 4 123 4567',
  email: 'hr@techcorp.ae',
  website: 'https://techcorp.ae',
  logoUrl: undefined,
  wpsEmployerCode: 'TC001234',
  wpsRoutingCode: 'ENBD',
  createdAt: '2024-01-01T00:00:00Z',
  updatedAt: '2024-12-01T00:00:00Z',
};

export const mockSubscription: Subscription = {
  id: 'sub-1',
  companyId: 'company-1',
  plan: 'business',
  status: 'active',
  currentPeriodStart: '2024-12-01',
  currentPeriodEnd: '2025-01-01',
  employeeLimit: 100,
  monthlyPrice: 499,
  currency: 'AED',
};

export const mockBillingHistory: BillingHistory[] = [
  {
    id: 'inv-1',
    date: '2024-12-01',
    description: 'Business Plan - Monthly',
    amount: 499,
    currency: 'AED',
    status: 'paid',
    invoiceUrl: '#',
  },
  {
    id: 'inv-2',
    date: '2024-11-01',
    description: 'Business Plan - Monthly',
    amount: 499,
    currency: 'AED',
    status: 'paid',
    invoiceUrl: '#',
  },
  {
    id: 'inv-3',
    date: '2024-10-01',
    description: 'Business Plan - Monthly',
    amount: 499,
    currency: 'AED',
    status: 'paid',
    invoiceUrl: '#',
  },
  {
    id: 'inv-4',
    date: '2024-09-01',
    description: 'Business Plan - Monthly',
    amount: 499,
    currency: 'AED',
    status: 'paid',
    invoiceUrl: '#',
  },
];

export const mockUsers: User[] = [
  {
    id: 'user-1',
    companyId: 'company-1',
    email: 'admin@techcorp.ae',
    firstName: 'Mohammed',
    lastName: 'Al Rashid',
    role: 'admin',
    isActive: true,
    lastLogin: '2024-12-15T09:30:00Z',
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-2',
    companyId: 'company-1',
    email: 'hr@techcorp.ae',
    firstName: 'Sara',
    lastName: 'Ahmed',
    role: 'hr_manager',
    isActive: true,
    lastLogin: '2024-12-15T08:45:00Z',
    createdAt: '2024-01-15T00:00:00Z',
    invitedBy: 'user-1',
  },
  {
    id: 'user-3',
    companyId: 'company-1',
    email: 'finance.manager@techcorp.ae',
    firstName: 'Khalid',
    lastName: 'Hassan',
    role: 'manager',
    isActive: true,
    lastLogin: '2024-12-14T16:20:00Z',
    createdAt: '2024-02-01T00:00:00Z',
    invitedBy: 'user-1',
  },
  {
    id: 'user-4',
    companyId: 'company-1',
    email: 'it.manager@techcorp.ae',
    firstName: 'Fatima',
    lastName: 'Noor',
    role: 'manager',
    isActive: true,
    lastLogin: '2024-12-13T11:00:00Z',
    createdAt: '2024-03-01T00:00:00Z',
    invitedBy: 'user-2',
  },
  {
    id: 'user-5',
    companyId: 'company-1',
    email: 'john.doe@techcorp.ae',
    firstName: 'John',
    lastName: 'Doe',
    role: 'employee',
    isActive: false,
    lastLogin: '2024-11-30T14:00:00Z',
    createdAt: '2024-04-01T00:00:00Z',
    invitedBy: 'user-2',
  },
];

export const mockSystemSettings: SystemSettings = {
  id: 'settings-1',
  companyId: 'company-1',
  ...DEFAULT_SYSTEM_SETTINGS,
};

export const mockNotificationSettings: NotificationSettings = {
  id: 'notif-1',
  companyId: 'company-1',
  userId: 'user-1',
  ...DEFAULT_NOTIFICATION_SETTINGS,
};
